const STATUSES=["Interview Requested","Interview Scheduled","Interview Completed","Assessment / Next Round","Awaiting Response","Offer Received","Offer Accepted / Active","Rejected","Withdrawn","Need Status Update"];
const PRIORITIES=["High","Medium","Low"];
const STAGES=["Recruiter Screen","One-way Video","Hiring Manager Interview","Final Interview","Technical Assessment","Offer / Onboarding","Unknown"];
const FILTERS=["All","Action","Active","Offers","Closed"];
const CLOSED=["Rejected","Withdrawn","Offer Accepted / Active"];
const OFFERS=["Offer Received","Offer Accepted / Active"];
let interviews=[],filter="All",search="",editingId=null,updatedAt=null,toastTimer;
const $=id=>document.getElementById(id);const form=$("editForm");
const iconPaths={search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',plus:'<path d="M12 5v14M5 12h14"/>',download:'<path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M5 19h14"/>',upload:'<path d="M12 21V9m0 0 4 4m-4-4-4 4"/><path d="M5 5h14"/>',save:'<path d="M5 4h12l2 2v14H5z"/><path d="M8 4v6h8V4M8 20v-6h8v6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',external:'<path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v7H4V6h7"/>',trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13"/>',more:'<circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/>'};
function icon(name,size=18){return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||""}</svg>`}
function hydrateIcons(){document.querySelectorAll("[data-icon]").forEach(el=>el.innerHTML=icon(el.dataset.icon))}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function cloneSeed(){return JSON.parse(JSON.stringify(window.SEED_DATA||[]))}
function normalizeDate(v){if(!v)return"";if(typeof v==="number"&&window.XLSX){const p=XLSX.SSF.parse_date_code(v);return p?`${p.y}-${String(p.m).padStart(2,"0")}-${String(p.d).padStart(2,"0")}`:""}const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v).slice(0,10):d.toISOString().slice(0,10)}
function formatDate(v){if(!v)return"";const[y,m,d]=String(v).slice(0,10).split("-").map(Number);return y&&m&&d?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(y,m-1,d)):""}
function followUpState(item){if(CLOSED.includes(item.status))return"closed";if(!item.followUpDate)return"missing";const today=new Date();today.setHours(0,0,0,0);const due=new Date(`${item.followUpDate}T00:00:00`);const diff=Math.round((due-today)/86400000);if(diff<0)return"overdue";if(diff===0)return"today";if(diff<=3)return"soon";return"upcoming"}
function statusTone(s){if(OFFERS.includes(s))return"success";if(s==="Rejected"||s==="Withdrawn")return"danger";if(s==="Need Status Update")return"warning";return"info"}
function shortStatus(s){return({"Need Status Update":"Needs update","Offer Accepted / Active":"Offer accepted","Assessment / Next Round":"Next round","Interview Requested":"Interview request","Interview Scheduled":"Scheduled","Interview Completed":"Completed","Awaiting Response":"Waiting","Offer Received":"Offer","Rejected":"Rejected","Withdrawn":"Closed"})[s]||s}
function followLabel(item){const state=followUpState(item);if(state==="closed")return"Closed";if(state==="missing")return"No follow-up date";if(state==="today")return"Follow up today";if(state==="overdue")return"Follow-up overdue";return `Follow up ${formatDate(item.followUpDate)}`}
function metrics(){const offers=interviews.filter(i=>OFFERS.includes(i.status)).length,closed=interviews.filter(i=>CLOSED.includes(i.status)).length,action=interviews.filter(i=>i.status==="Need Status Update"||["overdue","today","missing"].includes(followUpState(i))).length,active=interviews.filter(i=>!CLOSED.includes(i.status)&&i.status!=="Need Status Update").length;return{offers,closed,action,active,total:interviews.length}}
function setSync(state){const i=$("syncIndicator");i.className=`sync-indicator ${state}`;$("syncText").textContent=state==="cloud"?"Synced":state==="saving"?"Saving":state==="error"?"Sync issue":"On device";$("saveButton").disabled=state==="saving";$("saveButton").innerHTML=`${icon("save")}${state==="saving"?" Saving…":" Save online"}`;$("storageCopy").textContent=state==="cloud"?"Cloud data is current.":"Showing verified tracker data."}
function showToast(message){clearTimeout(toastTimer);const t=$("toast");t.textContent=message;t.hidden=false;toastTimer=setTimeout(()=>t.hidden=true,3200)}
function render(){renderSummary();renderFilters();renderFeed()}
function renderSummary(){const m=metrics();$("attentionCount").textContent=m.action;$("attentionNote").textContent=m.action?`${m.action} follow-up${m.action===1?"":"s"} or stale status${m.action===1?"":"es"}`:"Nothing urgent right now";$("metricGrid").innerHTML=[["Active",m.active,"moving"],["Offers",m.offers,"won"],["Closed",m.closed,"finished"]].map(([l,v,d])=>`<div class="metric-item"><span>${l}</span><strong>${v}</strong><small>${d}</small></div>`).join("")}
function renderFilters(){$("filterTabs").innerHTML=FILTERS.map(n=>`<button class="tab ${filter===n?"active":""}" data-filter="${n}">${n}</button>`).join("");document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()})}
function filteredRows(){const q=search.trim().toLowerCase(),followOrder={overdue:0,today:1,missing:2,soon:3,upcoming:4,closed:5},priority={High:0,Medium:1,Low:2};return[...interviews].filter(i=>{if(filter==="Action"&&i.status!=="Need Status Update"&&!["overdue","today","missing"].includes(followUpState(i)))return false;if(filter==="Active"&&(CLOSED.includes(i.status)||i.status==="Need Status Update"))return false;if(filter==="Offers"&&!OFFERS.includes(i.status))return false;if(filter==="Closed"&&!CLOSED.includes(i.status))return false;return !q||[i.company,i.role,i.status,i.stage,i.nextAction].join(" ").toLowerCase().includes(q)}).sort((a,b)=>followOrder[followUpState(a)]-followOrder[followUpState(b)]||priority[a.priority]-priority[b.priority])}
function renderFeed(){const rows=filteredRows();$("emptyState").hidden=rows.length>0;$("resultCount").textContent=`${rows.length} ${rows.length===1?"company":"companies"}`;$("feedTitle").textContent=filter==="All"?"Everything":filter;$("trackerBody").innerHTML=rows.map(item=>{const tone=statusTone(item.status),next=item.nextAction&&item.nextAction!=="Closed."?item.nextAction:(CLOSED.includes(item.status)?"No further action":"Check the latest status"),follow=followUpState(item),date=item.interviewDate?`Interview ${formatDate(item.interviewDate)}`:item.inviteDate?`Invited ${formatDate(item.inviteDate)}`:"Date not set";return `<article class="application-row tone-${tone}"><button class="application-button edit-entry" data-id="${item.id}" aria-label="Open ${escapeHtml(item.company)}"><div class="row-top"><div><h3 class="company-name">${escapeHtml(item.company)}</h3><p class="role-name">${escapeHtml(item.role)}</p></div><span class="status-label status-${tone}">${escapeHtml(shortStatus(item.status))}</span></div><div class="next-line"><span class="next-arrow">→</span><p>${escapeHtml(next)}</p></div><div class="row-foot"><span>${escapeHtml(item.stage||"Unknown")}</span><span>${escapeHtml(date)}</span><span class="follow-${follow}">${escapeHtml(followLabel(item))}</span></div></button></article>`}).join("");document.querySelectorAll(".edit-entry").forEach(b=>b.onclick=()=>openModal(Number(b.dataset.id)))}
function fillSelect(name,values){form.elements[name].innerHTML=values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join("")}
function openModal(id){editingId=id;const existing=interviews.find(i=>Number(i.id)===Number(id));const item=existing?{...existing}:{id,company:"",role:"",stage:"Recruiter Screen",inviteDate:new Date().toISOString().slice(0,10),interviewDate:"",status:"Interview Requested",priority:"Medium",nextAction:"",followUpDate:"",contact:"",mode:"",source:"",notes:""};$("modalTitle").textContent=existing?"Update status":"Add company";Object.entries(item).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v||""});$("deleteButton").hidden=!existing;$("sourceButton").hidden=!String(item.source).startsWith("http");$("sourceButton").href=String(item.source).startsWith("http")?item.source:"#";$("modalBackdrop").hidden=false;document.body.style.overflow="hidden"}
function closeModal(){$("modalBackdrop").hidden=true;document.body.style.overflow="";editingId=null}
function openTools(){$("toolsBackdrop").hidden=false;$("toolsButton").setAttribute("aria-expanded","true");document.body.style.overflow="hidden"}
function closeTools(){$("toolsBackdrop").hidden=true;$("toolsButton").setAttribute("aria-expanded","false");document.body.style.overflow=""}
function readForm(){const d=new FormData(form);return{id:editingId,company:String(d.get("company")||"").trim(),role:String(d.get("role")||"").trim(),stage:String(d.get("stage")||"Unknown"),inviteDate:String(d.get("inviteDate")||""),interviewDate:String(d.get("interviewDate")||""),status:String(d.get("status")||"Need Status Update"),priority:String(d.get("priority")||"Medium"),nextAction:String(d.get("nextAction")||"").trim(),followUpDate:String(d.get("followUpDate")||""),contact:String(d.get("contact")||"").trim(),mode:String(d.get("mode")||"").trim(),source:String(d.get("source")||"").trim(),notes:String(d.get("notes")||"").trim()}}
async function loadData(notify=false){const password=$("adminPassword").value||sessionStorage.getItem("interview-admin-password")||"";if(password){sessionStorage.setItem("interview-admin-password",password);$("adminPassword").value=password}try{const headers=password?{"x-admin-password":password}:{},response=await fetch("/api/tracker",{cache:"no-store",headers}),payload=await response.json().catch(()=>({}));if(response.status===401||response.status===503){interviews=cloneSeed();setSync("local");if(notify)showToast(response.status===401?"Incorrect password":"Cloud storage is not configured");render();return}if(!response.ok)throw new Error(payload.error||"Cloud tracker unavailable");interviews=Array.isArray(payload.data)&&payload.data.length?payload.data:cloneSeed();setSync(payload.cloud?"cloud":"local");updatedAt=payload.updatedAt||null;if(notify)showToast(payload.cloud?"Cloud tracker loaded":"Verified tracker loaded")}catch(error){interviews=cloneSeed();setSync("local");if(notify)showToast(error.message||"Showing verified tracker data")}updateLastSync();render()}
function updateLastSync(){$("lastSync").textContent=updatedAt?`Updated ${new Date(updatedAt).toLocaleString()}`:""}
async function saveOnline(){setSync("saving");const password=$("adminPassword").value;if(password)sessionStorage.setItem("interview-admin-password",password);try{const response=await fetch("/api/tracker",{method:"PUT",headers:{"Content-Type":"application/json","x-admin-password":password},body:JSON.stringify(interviews)}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Cloud save unavailable");updatedAt=payload.updatedAt;setSync("cloud");updateLastSync();closeTools();showToast("Saved online")}catch(error){setSync("local");showToast(error.message||"Could not save online")}}
function exportExcel(){const rows=interviews.map(i=>({ID:i.id,Company:i.company,Role:i.role,"Interview Stage":i.stage,"Invite Date":i.inviteDate,"Interview Date":i.interviewDate,"Current Status":i.status,Priority:i.priority,"Next Action":i.nextAction,"Follow-Up Date":i.followUpDate,"Contact / Recruiter":i.contact,"Mode / Location":i.mode,"Source / Evidence":i.source,Notes:i.notes}));if(window.XLSX){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Interview Tracker");XLSX.writeFile(wb,`Het_Job_Radar_${new Date().toISOString().slice(0,10)}.xlsx`);showToast("Excel exported")}else showToast("Excel library did not load")}
async function importFile(file){try{let mapped=[];if(file.name.toLowerCase().endsWith(".json"))mapped=JSON.parse(await file.text());else if(window.XLSX){const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=wb.Sheets[wb.SheetNames.includes("Interview Tracker")?"Interview Tracker":wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(sheet,{defval:""});mapped=data.map((r,index)=>({id:Number(r.ID||index+1),company:String(r.Company||""),role:String(r.Role||""),stage:String(r["Interview Stage"]||"Unknown"),inviteDate:normalizeDate(r["Invite Date"]),interviewDate:normalizeDate(r["Interview Date"]),status:String(r["Current Status"]||"Need Status Update"),priority:String(r.Priority||"Medium"),nextAction:String(r["Next Action"]||""),followUpDate:normalizeDate(r["Follow-Up Date"]),contact:String(r["Contact / Recruiter"]||""),mode:String(r["Mode / Location"]||""),source:String(r["Source / Evidence"]||""),notes:String(r.Notes||"")}))}else throw new Error("Excel library did not load");mapped=mapped.filter(i=>i.company||i.role);if(!mapped.length)throw new Error("No tracker rows found");interviews=mapped;render();closeTools();showToast(`Imported ${mapped.length} records — save online to sync`)}catch(error){showToast(error.message||"Could not import file")}}
fillSelect("stage",STAGES);fillSelect("status",STATUSES);fillSelect("priority",PRIORITIES);hydrateIcons();
$("searchInput").addEventListener("input",e=>{search=e.target.value;renderFeed()});$("addButton").onclick=()=>openModal(Math.max(0,...interviews.map(i=>Number(i.id)||0))+1);$("toolsButton").onclick=openTools;$("closeTools").onclick=closeTools;$("toolsBackdrop").addEventListener("mousedown",e=>{if(e.target===$("toolsBackdrop"))closeTools()});$("importButton").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>{const file=e.target.files[0];if(file)importFile(file);e.target.value=""};$("exportButton").onclick=exportExcel;$("saveButton").onclick=saveOnline;$("closeModal").onclick=closeModal;$("cancelButton").onclick=closeModal;$("modalBackdrop").addEventListener("mousedown",e=>{if(e.target===$("modalBackdrop"))closeModal()});$("adminPassword").value=sessionStorage.getItem("interview-admin-password")||"";$("adminPassword").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();loadData(true)}});form.addEventListener("submit",e=>{e.preventDefault();const item=readForm();if(!item.company||!item.role){showToast("Company and role are required");return}const index=interviews.findIndex(i=>Number(i.id)===Number(item.id));if(index>=0)interviews[index]=item;else interviews.push(item);closeModal();render();showToast("Status updated — use tools to save online")});$("deleteButton").onclick=()=>{const item=interviews.find(i=>Number(i.id)===Number(editingId));if(item&&confirm(`Delete ${item.company}?`)){interviews=interviews.filter(i=>Number(i.id)!==Number(editingId));closeModal();render();showToast("Company removed — use tools to save online")}};loadData();